/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShowOSXInfo */

#ifndef _Included_ShowOSXInfo
#define _Included_ShowOSXInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShowOSXInfo
 * Method:    getOSXInfo
 * Signature: ()LOSXInfo;
 */
JNIEXPORT jobject JNICALL Java_ShowOSXInfo_getOSXInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
